export const dataSet = [
    {
        img: '../images/library/1.jpg',
        title: 'Как правильно считать калории',
        link: 'https://telegra.ph/Kak-pravilno-schitat-kalorii-10-28',
        section: 'Процесс',
    },
    {
        img: '../images/library/2.jpg',
        title: 'Почему скачет вес и как оценивать прогресс? ',
        link: 'https://telegra.ph/Pochemu-skachet-ves-i-kak-ocenivat-progress-10-25',
        section: 'Физиология',
    },
    {
        img: '../images/library/3.jpeg',
        title: 'Как правильно выстраивать дефицит',
        link: 'https://telegra.ph/Kak-pravilno-vystraivat-deficit-ili-proficit-kalorijnosti-10-31',
        section: 'Процесс',
    },
    {
        img: '../images/library/4.jpeg',
        title: '8 причин которые могут  мешать худеть',
        link: 'https://telegra.ph/8-prichin-kotorye-mogut-meshat-hudet-10-25',
        section: 'Физиология',
    },
    {
        img: '../images/library/5.jpeg',
        title: 'Калории. Считать или нет? ',
        link: ' https://telegra.ph/Kalorii-Schitat-ili-net-10-25',
        section: 'Процесс',
    },
    {
        img: '../images/library/6.jpeg',
        title: 'Оптимальный процент жира в организме. На сколько худеть?',
        link: 'https://telegra.ph/Optimalnyj-procent-zhira-v-organizme-Na-skolko-hudet-10-26',
        section: 'Физиология',
    },
    {
        img: '../images/library/7.webp',
        title: 'Как жир покидает тело когда вы теряете вес?',
        link: 'https://telegra.ph/Kak-zhir-pokidaet-telo-kogda-vy-teryaete-ves-11-06',
        section: 'Физиология',
    },
    {
        img: '../images/library/8.jpg',
        title: 'Нужен ли завтрак?',
        link: 'https://telegra.ph/Nuzhen-li-zavtrak-11-06',
        section: 'Здоровье',
    },
    {
        img: '../images/library/9.jpg',
        title: 'Как правильно есть?',
        link: 'https://telegra.ph/Kak-pravilno-est-11-11',
        section: 'Здоровье',
    },
    {
        img: '../images/library/10.jpg',
        title: 'Что такое белок и зачем он нам?',
        link: 'https://telegra.ph/Belok-skolko-veshat-v-grammah-i-kakie-istochniki-vybrat-12-18',
        section: 'Здоровье',
    },
    {
        img: '../images/library/11.webp',
        title: 'Нормы и усвоение белка. Сколько есть?',
        link: 'https://telegra.ph/Normy-i-istochniki-belka-Kogda-i-skolko-est-12-19',
        section: 'Физиология',
    },
    {
        img: '../images/library/12.webp',
        title: 'Источники белка. Что и когда есть?',
        link: 'https://telegra.ph/Istochniki-belka-CHto-est-i-kak-raspredelyat-belok-v-techenie-dnya-12-29',
        section: 'Процесс',
    },
    {
        img: '../images/library/13.jpg',
        title: 'Потребление и усвоение белка, что меняется с возрастом? ',
        link: 'https://telegra.ph/Potreblenie-i-usvoenie-belka-chto-menyaetsya-s-vozrastom-01-01',
        section: 'Процесс',
    },
]