export const dataSet = [
    {
        img: '../../src/images/top-clients/avatar/AlexandraSemenova.png',
        name: 'Александра Семенова',
        info: 'Гимнастка',
        text: 'Заслуженный мастер спорта России по художественной гимнастике, чемпионка мира и Европы в групповых упражнениях, чемпионка Санкт-Петербурга в индивидуальном многоборье, призер чемпионата России',
        id: '1',
        modal_img: '../../src/images/top-clients/modal/AlexandraSemenova.png',
    },
    {
        img: '../../src/images/top-clients/avatar/SvatlanaVeselova.png',
        name: 'Светлана Веселова',
        info: 'Кроссфит-атлет',
        text: 'КМС по ТА, МС по функциональному многоборью, МС по пауэрлифтингу, 2-х кратная Чемпионка России по ФМ, выступающая кроссфит-атлетка категории элит, Top-5 четвертьфинального этапа отбора на CrossFit Games региона Азия',
        id: '2',
        modal_img: '../../src/images/top-clients/modal/SvetlanaVeselova.png',
    },
    {
        img: '../../src/images/top-clients/avatar/AndreyFedotov.png',
        name: 'Андрей Федотов',
        info: 'Кроссфит-атлет',
        text: 'Мастер спорта по дзюдо, призер и чемпион ЧР по функциональному многоборью, чемпион Москвы по ФМ, чемпион European Showdown 2019 в командном зачете',
        id: '3',
        modal_img: '../../src/images/top-clients/modal/AndreyFedotov.png',
    },
    {
        img: '../../src/images/top-clients/avatar/AndreyKovalev.png',
        name: 'Андрей Ковалев',
        info: 'Руководитель в Сбербанк',
        id: '4',
        modal_img: '../../src/images/top-clients/modal/AndreyKovalev.png',
    },
    {
        img: '../../src/images/top-clients/avatar/OlgaAfanaseva.png',
        name: 'Ольга Афанасьева',
        info: 'Тяжелоатлетка',
        id: '5',
        modal_img: '../../src/images/top-clients/modal/OlgaAfanaseva.png',
    },
    {
        img: '../../src/images/top-clients/avatar/VitalyStepanov.png',
        name: 'Виталий Степанов',
        info: 'Кроссфит-атлет',
        id: '6',
        modal_img: '../../src/images/top-clients/modal/VitalyStepanov.png',
    },
    {
        img: '../../src/images/top-clients/avatar/AlexeyKlimcev.png',
        name: 'Алексей Климцев',
        info: 'Боксер',
        id: '7',
        modal_img: '../../src/images/top-clients/modal/AlexeyKlimcev.png',
    },
    {
        img: '../../src/images/top-clients/avatar/AnastasiySmirnova.jpg',
        name: 'Анастасия Смирнова',
        info: 'Кроссфит-атлет',
        id: '9',
        modal_img: '../../src/images/top-clients/modal/AnastasiySmirnova.png',
    },
    {
        img: '../../src/images/top-clients/avatar/MikhailLitovchenko.png',
        name: 'Михаил Литовченко',
        info: 'Кроссфит-атлет',
        id: '10',
        modal_img: '../../src/images/top-clients/modal/MikhailLitovchenko.png',
    },
    {
        img: '../../src/images/top-clients/avatar/AlenaVasileva.png',
        name: 'Алена Васильева',
        info: 'Управляющая лингва центров',
        modal_img: '../../src/images/top-clients/modal/AlenaVasileva.png',
    },
    {
        img: '../../src/images/top-clients/avatar/YuriIvanov.jpg',
        name: 'Юрий Иванов',
        info: 'Agile-коуч',
        modal_img: '../../src/images/top-clients/modal/YuriIvanov.png',
    },
    {
        img: '../../src/images/top-clients/avatar/TatianaDmitrienko.png',
        name: 'Татьяна Дмитриенко',
        info: 'Управляющая лингва центров',
        modal_img: '../../src/images/top-clients/modal/TatianaDmitrienko.png',
    },
    {
        img: '../../src/images/top-clients/avatar/DmitryShvedun.png',
        name: 'Дмитрий Шведун',
        info: 'Фитнес-тренер',
        modal_img: '../../src/images/top-clients/modal/DmitryShvedun.png',
    },
    {
        img: '../../src/images/top-clients/avatar/AndreySkrybikov.png',
        name: 'Андрей Скрябиков',
        info: 'Управляющая лингва центров',
        modal_img: '../../src/images/top-clients/modal/AndreiSkrybikov.png',
    },
    {
        img: '../../src/images/top-clients/avatar/DmitryPronin.jpg',
        name: 'Дмитрий Пронин',
        info: 'Управляющая лингва центров',
        modal_img: '../../src/images/top-clients/modal/AndreiSkrybikov.png',
    },
]