export const dataSet = [
    {
        img: '../../src/images/top-clients/AlexSem.png',
        name: 'Александра Семенова',
        info: 'Гимнастка',
        text: 'Заслуженный мастер спорта России по художественной гимнастике, чемпионка мира и Европы в групповых упражнениях, чемпионка Санкт-Петербурга в индивидуальном многоборье, призер чемпионата России',
        id: '1',
        modal_img: '../../src/images/top-clients/SS_modal.png',
    },
    {
        img: '../../src/images/top-clients/SvetVes.png',
        name: 'Светлана Веселова',
        info: 'Кроссфит-атлет',
        text: 'КМС по ТА, МС по функциональному многоборью, МС по пауэрлифтингу, 2-х кратная Чемпионка России по ФМ, выступающая кроссфит-атлетка категории элит, Top-5 четвертьфинального этапа отбора на CrossFit Games региона Азия',
        id: '2',
        modal_img: '../../src/images/top-clients/SV_modal.png',
    },
    {
        img: '../../src/images/top-clients/AndFed.png',
        name: 'Андрей Федотов',
        info: 'Кроссфит-атлет',
        text: 'Мастер спорта по дзюдо, призер и чемпион ЧР по функциональному многоборью, чемпион Москвы по ФМ, чемпион European Showdown 2019 в командном зачете',
        id: '3',
        modal_img: '../../src/images/top-clients/AF_modal.png',
    },
    {
        img: '../../src/images/top-clients/AndKov.png',
        name: 'Андрей Ковалев',
        info: 'Руководитель в Сбербанк',
        id: '4',
        modal_img: '../../src/images/top-clients/AK_modal.png',
    },
    {
        img: '../../src/images/top-clients/OlgAfan.png',
        name: 'Ольга Афанасьева',
        info: 'Тяжелоатлетка',
        id: '5',
        modal_img: '../../src/images/top-clients/OA_modal.png',
    },
    {
        img: '../../src/images/top-clients/VitStep.png',
        name: 'Виталий Степанов',
        info: 'Кроссфит-атлет',
        id: '6',
        modal_img: '../../src/images/top-clients/VSt_modal.png',
    },
    {
        img: '../../src/images/top-clients/AlexKlim.png',
        name: 'Алексей Климцев',
        info: 'Боксер',
        id: '7',
        modal_img: '../../src/images/top-clients/Akl_modal.png',
    },
    {
        img: '../../src/images/avatar.webp',
        name: 'Елизавета Царева',
        info: 'Легкоатлетка',
        id: '8',
        modal_img: '../../src/images/top-clients/EC_modal.png',
    },
    {
        img: '../../src/images/top-clients/AnSm.png',
        name: 'Анастасия Смирнова',
        info: 'Кроссфит-атлет',
        id: '9',
        modal_img: '../../src/images/top-clients/AnSm_modal.png',
    },
    {
        img: '../../src/images/avatar.webp',
        name: 'Михаил Литовченко',
        info: 'Кроссфит-атлет',
        id: '10',
        modal_img: '../../src/images/top-clients/LM_modal.png',
    },
    {
        img: '../../src/images/top-clients/AlenEj.png',
        name: 'Алена Васильева',
        info: 'Управляющая лингва центров',
        modal_img: '../../src/images/top-clients/AlEj_modal.png',
    },
    {
        img: '../../src/images/top-clients/YurIv.jpg',
        name: 'Юрий Иванов',
        info: 'Управляющая лингва центров',
    },
    {
        img: '../../src/images/top-clients/TatDm.png',
        name: 'Татьяна Дмитриенко',
        info: 'Управляющая лингва центров',
        modal_img: '../../src/images/top-clients/TatDm_modal.png',
    },
    {
        img: '../../src/images/top-clients/DmShv.png',
        name: 'Дмитрий Шведун',
        info: 'Управляющая лингва центров',
    },
    {
        img: '../../src/images/top-clients/AndSkr.png',
        name: 'Андрей Скрябиков',
        info: 'Управляющая лингва центров',
    },
    {
        img: '../../src/images/top-clients/DmPr.jpg',
        name: 'Дмитрий Пронин',
        info: 'Управляющая лингва центров',
    },
    {
        img: '../../src/images/top-clients/AlenEj.png',
        name: 'Антон Мишин',
        info: 'Управляющая лингва центров',
    },
]