export const dataSet = [
    {
        img: 'nutrition-app/images/top-clients/avatar/AlexandraSemenova.png',
        name: 'Александра Семенова',
        info: 'Гимнастка',
        text: 'Заслуженный мастер спорта России по художественной гимнастике, чемпионка мира и Европы в групповых упражнениях, чемпионка Санкт-Петербурга в индивидуальном многоборье, призер чемпионата России',
        id: '1',
        modal_img: 'nutrition-app/images/top-clients/modal/AlexandraSemenova.png',
        quote: 'Помогли полностью разобраться в вопросах питания! Составили план, который отлично поддерживает меня на всех этапах подготовки. Научилась не только контролировать процесс, но и без ограничений быть всегда в соревновательном весе.',
        instagramLink: 'https://www.instagram.com/semenova_sasha__?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/SvatlanaVeselova.png',
        name: 'Светлана Веселова',
        info: 'Кроссфит-атлет',
        text: 'КМС по ТА, МС по функциональному многоборью, МС по пауэрлифтингу, 2-х кратная Чемпионка России по ФМ, выступающая кроссфит-атлетка категории элит, участница CrossFit Games',
        id: '2',
        modal_img: 'nutrition-app/images/top-clients/modal/SvetlanaVeselova.png',
        quote: 'С таким подходом и контролем моего питания чувствую себя уверенно перед любыми соревнованиями. Отличная работа в тандеме, рекомендую всем атлетам.',
        instagramLink: 'https://www.instagram.com/veselova_s?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/AndreyFedotov.png',
        name: 'Андрей Федотов',
        info: 'Кроссфит-атлет',
        text: 'Мастер спорта по дзюдо, призер ЧР по функциональному многоборью, чемпион Москвы, чемпион European Showdown, призер регионального этапа CrossFit Games',
        id: '3',
        modal_img: 'nutrition-app/images/top-clients/modal/AndreyFedotov.png',
        quote: 'Отлично поработали с командой BFN, корректировали рацион с учетом всех моих тренировочных нагрузок, плюс ребята добавили немного стабильности в режим.',
        instagramLink: 'https://www.instagram.com/1andreyfedotov?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/AndreyKovalev.png',
        name: 'Андрей Ковалев',
        info: 'Руководитель в Сбербанк',
        text: 'Активный участник локальных и корпоративных забегов, соревнований по кроссфиту, футболу',
        id: '4',
        modal_img: 'nutrition-app/images/top-clients/modal/AndreyKovalev.png',
        quote: 'Не ожидал, что правильное питание может быть таким простым! Ем вкусно, результаты идут вверх.',
        instagramLink: 'https://www.instagram.com/kovalevandrey28?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/OlgaAfanaseva.png',
        name: 'Ольга Афанасьева',
        text: '',
        info: 'Тяжелоатлетка',
        id: '5',
        modal_img: 'nutrition-app/images/top-clients/modal/OlgaAfanaseva.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/olgaafanaseva3003?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/VitalyStepanov.png',
        name: 'Виталий Степанов',
        text: '',
        info: 'Кроссфит-атлет',
        id: '6',
        modal_img: 'nutrition-app/images/top-clients/modal/VitalyStepanov.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/stepanov.w?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/AlexeyKlimcev.png',
        name: 'Алексей Климцев',
        text: '',
        info: 'Боксер',
        id: '7',
        modal_img: 'nutrition-app/images/top-clients/modal/AlexeyKlimcev.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/klinsmann86rus?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/AnastasiySmirnova.jpg',
        name: 'Анастасия Смирнова',
        text: '',
        info: 'Кроссфит-атлет',
        id: '9',
        modal_img: 'nutrition-app/images/top-clients/modal/AnastasiySmirnova.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/smirnova_anastasia_11?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/MikhailLitovchenko.png',
        name: 'Михаил Литовченко',
        info: 'Кроссфит-атлет',
        text: '',
        id: '10',
        modal_img: 'nutrition-app/images/top-clients/modal/MikhailLitovchenko.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/litovchenko__m?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/AlenaVasileva.png',
        name: 'Алена Васильева',
        info: 'Управляющая лингва центров',
        text: '',
        modal_img: 'nutrition-app/images/top-clients/modal/AlenaVasileva.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/alena.from.siberia?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/YuriIvanov.jpg',
        name: 'Юрий Иванов',
        info: 'Agile-коуч',
        text: '',
        modal_img: 'nutrition-app/images/top-clients/modal/YuriIvanov.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/juryivanov?igsh=MTVhMTU2ZHZkYWszag==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/TatianaDmitrienko.png',
        name: 'Татьяна Дмитриенко',
        info: 'Дизайнер МТС',
        text: '',
        modal_img: 'nutrition-app/images/top-clients/modal/TatianaDmitrienko.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/aaaaariva?igsh=MWMyeDBmeHQ3cWp6bA==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/DmitryShvedun.png',
        name: 'Дмитрий Шведун',
        info: 'Фитнес-тренер',
        text: '',
        modal_img: 'nutrition-app/images/top-clients/modal/DmitryShvedun.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/dima_shvedun?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/AndreySkrybikov.png',
        name: 'Андрей Скрябиков',
        info: 'Руководитель HR Леруа',
        text: '',
        modal_img: 'nutrition-app/images/top-clients/modal/AndreiSkrybikov.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/andrey_superrhero?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    },
    {
        img: 'nutrition-app/images/top-clients/avatar/DmitryPronin.jpg',
        name: 'Дмитрий Пронин',
        text: '',
        info: 'PM промышленной автоматики',
        modal_img: 'nutrition-app/images/top-clients/modal/AndreiSkrybikov.png',
        quote: '',
        instagramLink: 'https://www.instagram.com/dmitrypronin98?igsh=MTVpdzF6ZnRzMnZreg==',
    },
]